# Generated by Django 3.0.8 on 2020-07-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedNews',
            new_name='SavedNew',
        ),
    ]
