# Generated by Django 3.0.8 on 2020-07-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200719_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savednew',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='savednew',
            name='date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='savednew',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='savednew',
            name='source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='savednew',
            name='urlToImage',
            field=models.URLField(blank=True),
        ),
    ]
